Controllers/CategoryController.cs
using ETickets.Data;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ETickets.ViewModels;

namespace ETickets.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepositry CategoryRepositry;

        public CategoryController(ICategoryRepositry CategoryRepositry)
        {
            this.CategoryRepositry = CategoryRepositry;
        }

        public IActionResult Index()
        {

            var Categories = CategoryRepositry.GetCategories();
            var CategoriesVM = Categories.Select(e => new CategoryVM
            {
                Id = e.Id,
                Name = e.Name
            });
            return View(CategoriesVM);
        }
        public IActionResult MoviesByCategory(int id)
        {
            var category = CategoryRepositry.GetCategoryWithMovies(id);
            var categoryVM = new CategoryVM
            {
                Id = category.Id,
                Name = category.Name,
                Movies = category.Movies.Select(m => new MovieVM
                {
                    Id = m.Id,
                    Name = m.Name,
                    Description = m.Description,
                    Price = m.Price,
                    ImgUrl = m.ImgUrl,
                    TrailerUrl = m.TrailerUrl,
                    StartDate = m.StartDate,
                    EndDate = m.EndDate,
                    MovieStatus = m.MovieStatus,
                    CinemaId = m.CinemaId,
                    CinemaName = m.Cinema.Name,
                    CategoryName = m.Category.Name,
                    CategoryId = m.CategoryId
                }).ToList()
            };
            return View(categoryVM);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(CategoryVM categoryVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var category = new Category
                {
                    Id= categoryVM.Id,
                    Name = categoryVM.Name
                };
                CategoryRepositry.CreateCategory(category);
                CategoryRepositry.Save();

                return RedirectToAction("Index");
            /*}
            return View("CreateCategory", categoryVM);*/
        }
    }
}

Controllers/CinemaController.cs
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ETickets.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepositry CinemaRepositry;
        public CinemaController(ICinemaRepositry CinemaRepositry)
        {
            this.CinemaRepositry = CinemaRepositry;
        }

        public IActionResult Index()
        {
            var Cinemas = CinemaRepositry.GetCinemas();
            var CinemasVM = Cinemas.Select(c => new CinemaVM
            {
                Id = c.Id,
                Name = c.Name,
                Description = c.Description,
                Address = c.Address,
                CinemaLogo = c.CinemaLogo
            });
            return View(CinemasVM);
        }
        public IActionResult MoviesByCinema(int id)
        {
            var Cinema = CinemaRepositry.GetCinemasWithMovies(id);
            var cinemaVM = new CinemaVM
            {
                Id = Cinema.Id,
                Name = Cinema.Name,
                Description = Cinema.Description,
                Address = Cinema.Address,
                CinemaLogo = Cinema.CinemaLogo,
                Movies = Cinema.Movies.Select(m => new MovieVM
                {
                    Id = m.Id,
                    Name = m.Name,
                    Description = m.Description,
                    Price = m.Price,
                    ImgUrl = m.ImgUrl,
                    TrailerUrl = m.TrailerUrl,
                    StartDate = m.StartDate,
                    EndDate = m.EndDate,
                    MovieStatus = m.MovieStatus,
                    CinemaId = m.CinemaId,
                    CinemaName = m.Cinema.Name,
                    CategoryName = m.Category.Name,
                    CategoryId = m.CategoryId
                }).ToList()
            };
            return View(cinemaVM.Movies);
        }
    }
}

Controllers/MovieController.cs
using ETickets.Data.Enum;
using ETickets.Models;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ETickets.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepositry movieRepositry;
        private readonly ICategoryRepositry categoryRepositry;
        private readonly ICinemaRepositry cinemaRepositry;

        public MovieController(IMovieRepositry MovieRepositry , ICategoryRepositry CategoryRepositry , ICinemaRepositry CinemaRepositry )
        {
            this.movieRepositry = MovieRepositry;
            this.categoryRepositry = CategoryRepositry;
            this.cinemaRepositry = CinemaRepositry;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var movie = movieRepositry.GetMovieWithActors(id);
            movie.ViewCount += 1;
            movieRepositry.UpdateMovie(movie);
            movieRepositry.Save();
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CinemaName = movie.Cinema.Name,
                CategoryId = movie.CategoryId,
                CategoryName = movie.Category.Name,
                ViewCount = movie.ViewCount,
                Actors = movie.Actors.Select(a => new ActorVM
                {
                    Id = a.Id,
                    Bio = a.Bio,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    News = a.News,
                    ProfilePicture = a.ProfilePicture,
                    MoviesName = a.ActorMovies.Select(n => n.Movie.Name).ToList()
                }).ToList()
            };
            return View(movieVM);
        }

        public async Task<IActionResult> CreateMovie()
        {
            var movieVM = new MovieVM();
            ViewBag.Categories = new SelectList(categoryRepositry.GetCategories(), "Id", "Name");
            ViewBag.Cinemas = new SelectList(cinemaRepositry.GetCinemas(), "Id", "Name");
            return View(movieVM);
        }

        [HttpPost]
        public async Task<IActionResult> AddMovie(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = new Movie
                {
                    Id = movieVM.Id,
                    Name = movieVM.Name,
                    Description = movieVM.Description,
                    Price = movieVM.Price,
                    ImgUrl = movieVM.ImgUrl,
                    TrailerUrl = movieVM.TrailerUrl,
                    StartDate = movieVM.StartDate,
                    EndDate = movieVM.EndDate,
                    MovieStatus = movieVM.MovieStatus,
                    CinemaId = movieVM.CinemaId,
                    CategoryId = movieVM.CategoryId
                };
                await movieRepositry.CreateMovie(movie);
                return RedirectToAction("Index", "Home");
        /*  }
        var categories = categoryRepositry.GetCategories();
        ViewBag.Categories = new SelectList(categories, "Id", "Name");*/
        /*return View("CreateMovie", movieVM);*/
        }
        public IActionResult Edit(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            ViewBag.MovieStatuses = new SelectList(Enum.GetValues(typeof(MovieStatus)).Cast<MovieStatus>());
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CategoryId = movie.CategoryId
            };

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View(movieVM);
        }
        [HttpPost]
        public IActionResult SaveEdit(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = movieRepositry.GetMovie(movieVM.Id);

                movie.Name = movieVM.Name;
                movie.Description = movieVM.Description;
                movie.Price = movieVM.Price;
                movie.ImgUrl = movieVM.ImgUrl;
                movie.TrailerUrl = movieVM.TrailerUrl;
                movie.StartDate = movieVM.StartDate;
                movie.EndDate = movieVM.EndDate;
                movie.MovieStatus = movieVM.MovieStatus;
                movie.CinemaId = movieVM.CinemaId;
                movie.CategoryId = movieVM.CategoryId;

                movie.Actors = movieVM.Actors.Select(a => new Actor
                {
                    Id = a.Id,
                    News = a.News,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    Bio = a.Bio,
                    ProfilePicture = a.ProfilePicture
                }).ToList();

                movieRepositry.UpdateMovie(movie);
                movieRepositry.Save();

                return RedirectToAction("Index", "Movies");
            /*}

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View("Edit", movieVM);*/
        }
        /*public IActionResult BookAppointment(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            shoppingCartRepository.AddToCart(movie);
            TempData["Message"] = "Add ticket to cart success";
            return RedirectToAction("index");
        }*/
    }
}

Controllers/SearchController.cs
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace ETickets.Controllers
{
    public class SearchController : Controller
    {
        private readonly IMovieRepositry MovieRepositry;
        public SearchController(IMovieRepositry MovieRepositry)
        {
            this.MovieRepositry = MovieRepositry;
        }
        public IActionResult Index(string Name)
        {
            var searchResults = MovieRepositry.SearchMovies(Name);
            var searchResultsVM = searchResults.Select(m => new MovieVM
            {
                Id = m.Id,
                Name = m.Name,
                Description = m.Description,
                Price = m.Price,
                ImgUrl = m.ImgUrl,
                TrailerUrl = m.TrailerUrl,
                StartDate = m.StartDate,
                EndDate = m.EndDate,
                MovieStatus = m.MovieStatus,
                CinemaId = m.CinemaId,
                CinemaName = m.Cinema.Name,
                CategoryId = m.CategoryId,
                CategoryName = m.Category.Name
            });
            return View(searchResultsVM);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETickets</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETickets.styles.css" asp-append-version="true" />
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        .navbar-custom {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: #343a40;
        }

        .navbar-custom .navbar-left,
        .navbar-custom .navbar-right {
            display: flex;
            align-items: center;
        }

        .navbar-custom .navbar-brand img {
            width: 120px;
            height: 50px;
        }

        .navbar-custom .navbar-brand {
            color: #fff;
            font-size: 1.5rem;
            font-weight: bold;
        }

        .navbar-custom .navbar-nav .nav-link {
            color: #bbb;
            margin-right: 1rem;
        }

        .navbar-custom .navbar-nav .nav-link:hover {
            color: #fff;
        }

        .navbar-custom .form-control {
            border-radius: 0.25rem;
        }

        .navbar-custom .btn-outline-success {
            color: #fff;
            border-color: #28a745;
        }

        .navbar-custom .btn-outline-success:hover {
            background-color: #28a745;
            border-color: #28a745;
        }

        footer {
            background-color: #343a40;
            color: #bbb;
            padding: 1rem 0;
            text-align: center;
        }

        footer a {
            color: #28a745;
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom">
            <div class="container-fluid">
                <div class="navbar-left">
                    <a class="navbar-brand" href="#">
                        <img src="/images/logo.png" alt="Bootstrap">
                    </a>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Point</a>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Add
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Movie" asp-action="CreateMovie">Add Movie</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="CreateCategory">Add Category</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="navbar-right">
                    <form class="d-flex" role="search" action="@(Url.Action("Index", "Search"))" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="Name">
                        <button class="btn btn-outline-success" type="submit">
                            Search
                        </button>
                    </form>
                    <a class="nav-link" href="@Url.Action("Index", "ShoppingCart")">
                        <img src="https://img.icons8.com/ios-filled/50/ffd700/shopping-cart.png" width="30" height="30" alt="Cart" />
                        @* <span id="cart-count" class="badge badge-pill badge-danger">@Model.CartItemCount</span> *@
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="padding: 0.4rem 0;">
        <div class="container">
            &copy; 2024 - ETickets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>