Models/Cinema.cs
namespace ETickets.Models
{
    public class Cinema
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CinemaLogo { get; set; }
        public string Address { get; set; }
        public List<Movie> Movies { get; set; }
    }
}

Controllers/CategoryController.cs
using ETickets.Data;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ETickets.ViewModels;

namespace ETickets.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepositry CategoryRepositry;

        public CategoryController(ICategoryRepositry CategoryRepositry)
        {
            this.CategoryRepositry = CategoryRepositry;
        }

        public IActionResult Index()
        {

            var Categories = CategoryRepositry.GetCategories();
            var CategoriesVM = Categories.Select(e => new CategoryVM
            {
                Id = e.Id,
                Name = e.Name
            });
            return View(CategoriesVM);
        }
        public IActionResult MoviesByCategory(int id)
        {
            var category = CategoryRepositry.GetCategoryWithMovies(id);
            var categoryVM = new CategoryVM
            {
                Id = category.Id,
                Name = category.Name,
                Movies = category.Movies.Select(m => new MovieVM
                {
                    Id = m.Id,
                    Name = m.Name,
                    Description = m.Description,
                    Price = m.Price,
                    ImgUrl = m.ImgUrl,
                    TrailerUrl = m.TrailerUrl,
                    StartDate = m.StartDate,
                    EndDate = m.EndDate,
                    MovieStatus = m.MovieStatus,
                    CinemaId = m.CinemaId,
                    CinemaName = m.Cinema.Name,
                    CategoryName = m.Category.Name,
                    CategoryId = m.CategoryId
                }).ToList()
            };
            return View(categoryVM);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(CategoryVM categoryVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var category = new Category
                {
                    Id= categoryVM.Id,
                    Name = categoryVM.Name
                };
                CategoryRepositry.CreateCategory(category);
                CategoryRepositry.Save();

                return RedirectToAction("Index");
            /*}
            return View("CreateCategory", categoryVM);*/
        }
    }
}

Controllers/CinemaController.cs
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ETickets.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepositry CinemaRepositry;
        public CinemaController(ICinemaRepositry CinemaRepositry)
        {
            this.CinemaRepositry = CinemaRepositry;
        }

        public IActionResult Index()
        {
            var Cinemas = CinemaRepositry.GetCinemas();
            var CinemasVM = Cinemas.Select(c => new CinemaVM
            {
                Id = c.Id,
                Name = c.Name,
                Description = c.Description,
                Address = c.Address,
                CinemaLogo = c.CinemaLogo
            });
            return View(CinemasVM);
        }
        public IActionResult MoviesByCinema(int id)
        {
            var Cinema = CinemaRepositry.GetCinemasWithMovies(id);
            var cinemaVM = new CinemaVM
            {
                Id = Cinema.Id,
                Name = Cinema.Name,
                Description = Cinema.Description,
                Address = Cinema.Address,
                CinemaLogo = Cinema.CinemaLogo,
                Movies = Cinema.Movies.Select(m => new MovieVM
                {
                    Id = m.Id,
                    Name = m.Name,
                    Description = m.Description,
                    Price = m.Price,
                    ImgUrl = m.ImgUrl,
                    TrailerUrl = m.TrailerUrl,
                    StartDate = m.StartDate,
                    EndDate = m.EndDate,
                    MovieStatus = m.MovieStatus,
                    CinemaId = m.CinemaId,
                    CinemaName = m.Cinema.Name,
                    CategoryName = m.Category.Name,
                    CategoryId = m.CategoryId
                }).ToList()
            };
            return View(cinemaVM.Movies);
        }
    }
}

Controllers/MovieController.cs
using ETickets.Data.Enum;
using ETickets.Models;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ETickets.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepositry movieRepositry;
        private readonly ICategoryRepositry categoryRepositry;
        private readonly ICinemaRepositry cinemaRepositry;

        public MovieController(IMovieRepositry MovieRepositry , ICategoryRepositry CategoryRepositry , ICinemaRepositry CinemaRepositry )
        {
            this.movieRepositry = MovieRepositry;
            this.categoryRepositry = CategoryRepositry;
            this.cinemaRepositry = CinemaRepositry;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var movie = movieRepositry.GetMovieWithActors(id);
            movie.ViewCount += 1;
            movieRepositry.UpdateMovie(movie);
            movieRepositry.Save();
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CinemaName = movie.Cinema.Name,
                CategoryId = movie.CategoryId,
                CategoryName = movie.Category.Name,
                ViewCount = movie.ViewCount,
                Actors = movie.Actors.Select(a => new ActorVM
                {
                    Id = a.Id,
                    Bio = a.Bio,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    News = a.News,
                    ProfilePicture = a.ProfilePicture,
                    MoviesName = a.ActorMovies.Select(n => n.Movie.Name).ToList()
                }).ToList()
            };
            return View(movieVM);
        }

        public async Task<IActionResult> CreateMovie()
        {
            var movieVM = new MovieVM();
            ViewBag.Categories = new SelectList(categoryRepositry.GetCategories(), "Id", "Name");
            ViewBag.Cinemas = new SelectList(cinemaRepositry.GetCinemas(), "Id", "Name");
            return View(movieVM);
        }

        [HttpPost]
        public async Task<IActionResult> AddMovie(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = new Movie
                {
                    Id = movieVM.Id,
                    Name = movieVM.Name,
                    Description = movieVM.Description,
                    Price = movieVM.Price,
                    ImgUrl = movieVM.ImgUrl,
                    TrailerUrl = movieVM.TrailerUrl,
                    StartDate = movieVM.StartDate,
                    EndDate = movieVM.EndDate,
                    MovieStatus = movieVM.MovieStatus,
                    CinemaId = movieVM.CinemaId,
                    CategoryId = movieVM.CategoryId
                };
                await movieRepositry.CreateMovie(movie);
                return RedirectToAction("Index", "Home");
        /*  }
        var categories = categoryRepositry.GetCategories();
        ViewBag.Categories = new SelectList(categories, "Id", "Name");*/
        /*return View("CreateMovie", movieVM);*/
        }
        public IActionResult Edit(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            ViewBag.MovieStatuses = new SelectList(Enum.GetValues(typeof(MovieStatus)).Cast<MovieStatus>());
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CategoryId = movie.CategoryId
            };

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View(movieVM);
        }
        [HttpPost]
        public IActionResult SaveEdit(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = movieRepositry.GetMovie(movieVM.Id);

                movie.Name = movieVM.Name;
                movie.Description = movieVM.Description;
                movie.Price = movieVM.Price;
                movie.ImgUrl = movieVM.ImgUrl;
                movie.TrailerUrl = movieVM.TrailerUrl;
                movie.StartDate = movieVM.StartDate;
                movie.EndDate = movieVM.EndDate;
                movie.MovieStatus = movieVM.MovieStatus;
                movie.CinemaId = movieVM.CinemaId;
                movie.CategoryId = movieVM.CategoryId;

                movie.Actors = movieVM.Actors.Select(a => new Actor
                {
                    Id = a.Id,
                    News = a.News,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    Bio = a.Bio,
                    ProfilePicture = a.ProfilePicture
                }).ToList();

                movieRepositry.UpdateMovie(movie);
                movieRepositry.Save();

                return RedirectToAction("Index", "Movies");
            /*}

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View("Edit", movieVM);*/
        }
        /*public IActionResult BookAppointment(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            shoppingCartRepository.AddToCart(movie);
            TempData["Message"] = "Add ticket to cart success";
            return RedirectToAction("index");
        }*/
    }
}

Controllers/ShoppingCartController.cs
using ETickets.Data.Enum;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using Microsoft.AspNetCore.Mvc;

namespace ETickets.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartRepositry shoppingCart;
        private readonly IMovieRepositry movieRepositry;

        public ShoppingCartController(IShoppingCartRepositry shoppingCart , IMovieRepositry movieRepositry)
        {
            this.shoppingCart = shoppingCart;
            this.movieRepositry = movieRepositry;
        }
        public IActionResult Index()
        {
            var items = shoppingCart.GetShoppingCartItems();
            return View(items);
        }
        public IActionResult AddToCart(int id)
        {
            var movie = movieRepositry.GetMovie(id);

            if (movie == null)
            {
                return NotFound("Movie not found.");
            }

            if (movie.MovieStatus == MovieStatus.Expired || movie.MovieStatus == MovieStatus.UpComing)
            {
                TempData["Message"] = "Cannot add ticket to cart for this movie.";
                return RedirectToAction("Index", "Home");
            }

            shoppingCart.AddToCart(movie, 1);
            shoppingCart.Save();
            TempData["Message"] = "Add ticket to cart is success!";
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            if (movie != null)
            {
                shoppingCart.RemoveFromCart(movie);
            }
            shoppingCart.Save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult ClearCart()
        {
            shoppingCart.ClearCart();
            shoppingCart.Save();
            return RedirectToAction("Index");
        }
        public IActionResult Checkout()
        {
            shoppingCart.ClearCart();
            shoppingCart.Save();
            TempData["MessageCheckout"] = "Payment successful !";
            return RedirectToAction("Index" , "Home");
        }
    }
}

Views/Cinema/Index.cshtml
@model IEnumerable<ETickets.ViewModels.CinemaVM>

@{
    ViewData["Title"] = "Cinemas";
}

<h2>Cinemas</h2>

<div class="container">
    <div class="row">
        @foreach (var Cinema in Model)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@Cinema.Name</h5>
                        <a href="@Url.Action("MoviesByCinema", "Cinema", new { id = Cinema.Id })" class="btn btn-primary">All Movies</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Cinema/MoviesByCinema.cshtml
@model IEnumerable<ETickets.ViewModels.MovieVM>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Movies By Cinema</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-jcKcQCErjBujtCGRkXJg9t4Vun3b6nxu6R4+4Ol5KH4R/9fGk7XRoylo1HAoF5zN" crossorigin="anonymous">
    <style>
        .movie-title-box {
            background-color: #343a40;
            color: #fff;
            text-align: center;
            padding: 10px;
            margin-bottom: 10px;
            font-weight: bold;
        }

        .btn-status {
            border-radius: 0.25rem;
            font-weight: bold;
            width: 100%;
            text-align: center;
            padding: 0.5rem 1rem;
            cursor: pointer;
            transition: background-color 0.3s ease, border-color 0.3s ease, color 0.3s ease;
        }

            .btn-status.upcoming {
                background-color: #ffc107;
                color: #212529;
                border-color: #ffc107;
            }

            .btn-status.available {
                background-color: #28a745;
                color: #fff;
                border-color: #28a745;
            }

            .btn-status.expired {
                background-color: #dc3545;
                color: #fff;
                border-color: #dc3545;
            }

            .btn-status:hover {
                opacity: 0.85;
            }

            .btn-status:active,
            .btn-status:focus {
                outline: none;
                box-shadow: none;
            }

        .movie-card {
            margin-bottom: 20px;
        }

        .btn-container {
            display: flex;
            justify-content: space-between;
        }

            .btn-container .btn {
                flex: 1;
                margin-right: 5px;
            }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h2>Movies By Cinema</h2>
        <div class="row">
            @foreach (var movie in Model)
            {
                string btnClass = "btn-status upcoming";

                switch (movie.MovieStatus)
                {
                    case ETickets.Data.Enum.MovieStatus.Available:
                        btnClass = "btn-status available";
                        break;
                    case ETickets.Data.Enum.MovieStatus.Expired:
                        btnClass = "btn-status expired";
                        break;
                    case ETickets.Data.Enum.MovieStatus.UpComing:
                        btnClass = "btn-status upcoming";
                        break;
                }

                <div class="col-md-6 mb-4 movie-card">
                    <div class="card">
                        <div class="movie-title-box">
                            @movie.Name
                        </div>
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="~/images/movies/@movie.ImgUrl" class="card-img" alt="@movie.Name" style="height: 100%; width: 100%; object-fit: cover;">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <p class="card-text"><strong>Price:</strong> $@movie.Price</p>
                                    <p class="card-text"><strong>Cinema:</strong> @(movie.CinemaName != null ? movie.CinemaName : "N/A")</p>
                                    <p class="card-text"><strong>Dates:</strong> @movie.StartDate.ToString("MMMM dd, yyyy") - @movie.EndDate.ToString("MMMM dd, yyyy")</p>
                                    <p class="card-text"><strong>Category:</strong> <a href="@Url.Action("MoviesByCategory", "Category", new { id = movie.CategoryId })">@movie.CategoryName</a></p>
                                    <p class="card-text"><strong>Status:</strong> @movie.MovieStatus</p>
                                    <div class="btn-container">
                                        <a class="btn btn-primary" href="@Url.Action("Details", "Movie", new { id = movie.Id })">More Details</a>
                                        <a class="@btnClass btn btn-success" href="@Url.Action("AddToCart", "ShoppingCart", new { id = movie.Id })">Book Ticket</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4Agx1FTxjt5F5mNtv1ujC8i45aF7t5c7p4zFZB6WWU+DLs0yI7AY" crossorigin="anonymous"></script>
</body>
</html>