Models/Movie.cs
using ETickets.Data.Enum;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ETickets.Models
{
    public class Movie
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public double Price { get; set; }

        public string ImgUrl { get; set; }

        public string TrailerUrl { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public MovieStatus MovieStatus { get; set; }

        public int CinemaId { get; set; }

        public int CategoryId { get; set; }

        public int ViewCount { get; set; }

        public Cinema Cinema { get; set; }
        public Category Category { get; set; }
        public List<Actor> Actors { get; set; }
        public List<ActorMovie> ActorMovies { get; set; }
        /*        public List<OrderItem> OrderItems { get; set; }
        */
    }
}

Controllers/ActorController.cs
using ETickets.Models;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ETickets.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepositry ActorRepositry;

        public ActorController(IActorRepositry ActorRepositry)
        {
            this.ActorRepositry = ActorRepositry;
        }
        public IActionResult Index(int id)
        {
            var Actor = ActorRepositry.GetActorWithMovie(id);
            var actorVM = new ActorVM
            {
                Id = id,
                FirstName = Actor.FirstName,
                LastName = Actor.LastName,
                Bio = Actor.Bio,
                ProfilePicture = Actor.ProfilePicture,
                News = Actor.News,
                MoviesName = Actor.ActorMovies.Select(n => n.Movie.Name).ToList()
            };

            return View(actorVM);
        }

    }
}

Controllers/MovieController.cs
using ETickets.Data.Enum;
using ETickets.Models;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using ETickets.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ETickets.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepositry movieRepositry;
        private readonly ICategoryRepositry categoryRepositry;
        private readonly ICinemaRepositry cinemaRepositry;

        public MovieController(IMovieRepositry MovieRepositry , ICategoryRepositry CategoryRepositry , ICinemaRepositry CinemaRepositry )
        {
            this.movieRepositry = MovieRepositry;
            this.categoryRepositry = CategoryRepositry;
            this.cinemaRepositry = CinemaRepositry;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var movie = movieRepositry.GetMovieWithActors(id);
            movie.ViewCount += 1;
            movieRepositry.UpdateMovie(movie);
            movieRepositry.Save();
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CinemaName = movie.Cinema.Name,
                CategoryId = movie.CategoryId,
                CategoryName = movie.Category.Name,
                ViewCount = movie.ViewCount,
                Actors = movie.Actors.Select(a => new ActorVM
                {
                    Id = a.Id,
                    Bio = a.Bio,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    News = a.News,
                    ProfilePicture = a.ProfilePicture,
                    MoviesName = a.ActorMovies.Select(n => n.Movie.Name).ToList()
                }).ToList()
            };
            return View(movieVM);
        }

        public async Task<IActionResult> CreateMovie()
        {
            var movieVM = new MovieVM();
            ViewBag.Categories = new SelectList(categoryRepositry.GetCategories(), "Id", "Name");
            ViewBag.Cinemas = new SelectList(cinemaRepositry.GetCinemas(), "Id", "Name");
            return View(movieVM);
        }

        [HttpPost]
        public async Task<IActionResult> AddMovie(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = new Movie
                {
                    Id = movieVM.Id,
                    Name = movieVM.Name,
                    Description = movieVM.Description,
                    Price = movieVM.Price,
                    ImgUrl = movieVM.ImgUrl,
                    TrailerUrl = movieVM.TrailerUrl,
                    StartDate = movieVM.StartDate,
                    EndDate = movieVM.EndDate,
                    MovieStatus = movieVM.MovieStatus,
                    CinemaId = movieVM.CinemaId,
                    CategoryId = movieVM.CategoryId
                };
                await movieRepositry.CreateMovie(movie);
                return RedirectToAction("Index", "Home");
        /*  }
        var categories = categoryRepositry.GetCategories();
        ViewBag.Categories = new SelectList(categories, "Id", "Name");*/
        /*return View("CreateMovie", movieVM);*/
        }
        public IActionResult Edit(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            ViewBag.MovieStatuses = new SelectList(Enum.GetValues(typeof(MovieStatus)).Cast<MovieStatus>());
            var movieVM = new MovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImgUrl = movie.ImgUrl,
                TrailerUrl = movie.TrailerUrl,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieStatus = movie.MovieStatus,
                CinemaId = movie.CinemaId,
                CategoryId = movie.CategoryId
            };

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View(movieVM);
        }
        [HttpPost]
        public IActionResult SaveEdit(MovieVM movieVM)
        {
            /*if (ModelState.IsValid)
            {*/
                var movie = movieRepositry.GetMovie(movieVM.Id);

                movie.Name = movieVM.Name;
                movie.Description = movieVM.Description;
                movie.Price = movieVM.Price;
                movie.ImgUrl = movieVM.ImgUrl;
                movie.TrailerUrl = movieVM.TrailerUrl;
                movie.StartDate = movieVM.StartDate;
                movie.EndDate = movieVM.EndDate;
                movie.MovieStatus = movieVM.MovieStatus;
                movie.CinemaId = movieVM.CinemaId;
                movie.CategoryId = movieVM.CategoryId;

                movie.Actors = movieVM.Actors.Select(a => new Actor
                {
                    Id = a.Id,
                    News = a.News,
                    FirstName = a.FirstName,
                    LastName = a.LastName,
                    Bio = a.Bio,
                    ProfilePicture = a.ProfilePicture
                }).ToList();

                movieRepositry.UpdateMovie(movie);
                movieRepositry.Save();

                return RedirectToAction("Index", "Movies");
            /*}

            var categories = categoryRepositry.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", movieVM.CategoryId);

            return View("Edit", movieVM);*/
        }
        /*public IActionResult BookAppointment(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            shoppingCartRepository.AddToCart(movie);
            TempData["Message"] = "Add ticket to cart success";
            return RedirectToAction("index");
        }*/
    }
}

Controllers/ShoppingCartController.cs
using ETickets.Data.Enum;
using ETickets.Repositry;
using ETickets.Repositry.IRepositry;
using Microsoft.AspNetCore.Mvc;

namespace ETickets.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartRepositry shoppingCart;
        private readonly IMovieRepositry movieRepositry;

        public ShoppingCartController(IShoppingCartRepositry shoppingCart , IMovieRepositry movieRepositry)
        {
            this.shoppingCart = shoppingCart;
            this.movieRepositry = movieRepositry;
        }
        public IActionResult Index()
        {
            var items = shoppingCart.GetShoppingCartItems();
            return View(items);
        }
        public IActionResult AddToCart(int id)
        {
            var movie = movieRepositry.GetMovie(id);

            if (movie == null)
            {
                return NotFound("Movie not found.");
            }

            if (movie.MovieStatus == MovieStatus.Expired || movie.MovieStatus == MovieStatus.UpComing)
            {
                TempData["Message"] = "Cannot add ticket to cart for this movie.";
                return RedirectToAction("Index", "Home");
            }

            shoppingCart.AddToCart(movie, 1);
            shoppingCart.Save();
            TempData["Message"] = "Add ticket to cart is success!";
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int id)
        {
            var movie = movieRepositry.GetMovie(id);
            if (movie != null)
            {
                shoppingCart.RemoveFromCart(movie);
            }
            shoppingCart.Save();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult ClearCart()
        {
            shoppingCart.ClearCart();
            shoppingCart.Save();
            return RedirectToAction("Index");
        }
        public IActionResult Checkout()
        {
            shoppingCart.ClearCart();
            shoppingCart.Save();
            TempData["MessageCheckout"] = "Payment successful !";
            return RedirectToAction("Index" , "Home");
        }
    }
}

Views/Movie/CreateMovie.cshtml
@using ETickets.ViewModels
@model MovieVM

<h2>Create Movie</h2>

<partial name="_ValidationScriptsPartial" />

<form asp-action="AddMovie" method="post">
    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" placeholder="Enter movie name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control" placeholder="Enter movie description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" placeholder="Enter movie price" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ImgUrl" class="control-label"></label>
        <input asp-for="ImgUrl" class="form-control" placeholder="Enter image URL" />
        <span asp-validation-for="ImgUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TrailerUrl" class="control-label"></label>
        <input asp-for="TrailerUrl" class="form-control" placeholder="Enter trailer URL" />
        <span asp-validation-for="TrailerUrl" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="StartDate" class="control-label"></label>
        <input asp-for="StartDate" type="datetime-local" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="EndDate" class="control-label"></label>
        <input asp-for="EndDate" type="datetime-local" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="MovieStatus" class="control-label"></label>
        <select asp-for="MovieStatus" class="form-control">
            <option value="0">Upcoming</option>
            <option value="1">Available</option>
            <option value="2">Expired</option>
        </select>
        <span asp-validation-for="MovieStatus" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CinemaId" class="control-label"></label>
        <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
        <span asp-validation-for="CinemaId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CategoryId" class="control-label"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">
        <i class="bi bi-save"></i> Create
    </button>
</form>

Views/Movie/Details.cshtml
@model ETickets.ViewModels.MovieVM

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Movie Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-jcKcQCErjBujtCGRkXJg9t4Vun3b6nxu6R4+4Ol5KH4R/9fGk7XRoylo1HAoF5zN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.plyr.io/3.6.4/plyr.css">
    <style>
        .movie-details {
            max-width: 800px;
            margin: auto;
            padding: 20px;
        }

        .movie-img {
            width: 100%;
            height: auto;
            border-radius: 10px;
        }

        .movie-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

            .movie-header h2 {
                margin: 0;
            }

        .movie-info {
            margin-top: 20px;
        }

        .cast-images {
            margin-top: 20px;
        }

            .cast-images img {
                max-width: 100px;
                border-radius: 50%;
                margin-right: 10px;
            }

        .btn-status {
            border-radius: 0.25rem;
            font-weight: bold;
            text-align: center;
            padding: 0.5rem 1rem;
            cursor: pointer;
            transition: background-color 0.3s ease, border-color 0.3s ease, color 0.3s ease;
        }

            .btn-status.upcoming {
                background-color: #ffc107;
                color: #212529;
                border-color: #ffc107;
            }

            .btn-status.available {
                background-color: #28a745;
                color: #fff;
                border-color: #28a745;
            }

            .btn-status.expired {
                background-color: #dc3545;
                color: #fff;
                border-color: #dc3545;
            }

            .btn-status:hover {
                opacity: 0.85;
            }

            .btn-status:active,
            .btn-status:focus {
                outline: none;
                box-shadow: none;
            }
    </style>
</head>
<body>
    <div class="container movie-details mt-5">
        <div class="row">
            <div class="col-md-4">
                <img src="~/images/movies/@Model.ImgUrl" alt="@Model.Name" class="movie-img" />
                <div class="mt-3">
                    @{
                        string btnClass = "btn-status upcoming";
                        switch (Model.MovieStatus)
                        {
                            case ETickets.Data.Enum.MovieStatus.Available:
                                btnClass = "btn-status available";
                                break;
                            case ETickets.Data.Enum.MovieStatus.Expired:
                                btnClass = "btn-status expired";
                                break;
                            case ETickets.Data.Enum.MovieStatus.UpComing:
                                btnClass = "btn-status upcoming";
                                break;
                        }
                    }
                    @if (Model.MovieStatus == ETickets.Data.Enum.MovieStatus.Available)
                    {
                        <a href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.Id })" class="btn btn-success ml-2">Book Ticket</a>
                    }
                    else if (Model.MovieStatus == ETickets.Data.Enum.MovieStatus.UpComing)
                    {
                        <a class="btn btn-warning ml-2" disabled>Soon</a>
                    }
                    else
                    {
                        <a class="btn btn-danger ml-2" disabled>Not Available</a>
                    }
                </div>
            </div>
            <div class="col-md-8">
                <div class="movie-header">
                    <h2>@Model.Name</h2>
                    <span class="badge badge-info">@Model.MovieStatus</span>
                </div>
                <div class="movie-info">
                    <p class="lead">@Model.Description</p>
                    <p><strong>Price:</strong> $@Model.Price</p>
                    <p><strong>Cinema:</strong> @Model.CinemaName</p>
                    <p><strong>Category:</strong> @Model.CategoryName</p>
                    <p><strong>Start Date:</strong> @Model.StartDate.ToShortDateString()</p>
                    <p><strong>End Date:</strong> @Model.EndDate.ToShortDateString()</p>
                    <p>Views: @Model.ViewCount</p>

                    <div class="container movie-details mt-3">
                        <div class="movie-info">
                            <h4>Actors</h4>
                            @if (Model.Actors != null && Model.Actors.Any())
                            {
                                <div class="row">
                                    @foreach (var actor in Model.Actors)
                                    {
                                        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
                                            <div class="text-center">
                                                <a href="@Url.Action("Index", "Actor", new { id = actor.Id })">
                                                    <img src="~/images/cast/@actor.ProfilePicture" alt="@actor.FirstName" class="actor-img img-fluid" />
                                                </a>
                                                <p>@actor.FirstName @actor.LastName</p>
                                            </div>
                                        </div>
                                    }
                                </div>
                            }
                            else
                            {
                                <p>No actors available for this movie.</p>
                            }

                            <style>
                                .actor-img {
                                    width: 100%;
                                    height: auto;
                                    max-height: 150px;
                                    object-fit: cover;
                                    border-radius: 10px;
                                    margin-bottom: 10px;
                                }

                                .text-center p {
                                    margin: 0;
                                }
                            </style>
                    </div>

                    @* Video Trailer *@
                    <div class="mt-3">
                        <h4>Trailer</h4>
                        <div class="plyr__video-embed" id="player">
                            <iframe src="https://www.youtube.com/embed/@Model.TrailerUrl?origin=https://example.com"
                                    allowfullscreen
                                    allowtransparency
                                    allow="autoplay"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4Agx1FTxjt5F5mNtv1ujC8i45aF7t5c7p4zFZB6WWU+DLs0yI7AY" crossorigin="anonymous"></script>
    <script src="https://cdn.plyr.io/3.6.4/plyr.js"></script>
    <script>
        const player = new Plyr('#player');
    </script>
</body>
</html>

Views/Movie/Edit.cshtml
@model ETickets.ViewModels.MovieVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MovieVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrailerUrl" class="control-label"></label>
                <input asp-for="TrailerUrl" class="form-control" />
                <span asp-validation-for="TrailerUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieStatus" class="control-label"></label>
                <select asp-for="MovieStatus" class="form-control" asp-items="ViewBag.MovieStatuses"></select>
                <span asp-validation-for="MovieStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CinemaId" class="control-label"></label>
                <input asp-for="CinemaId" class="form-control" />
                <span asp-validation-for="CinemaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}